pipelines:
  - pipeline:
      name: 'Sync users/companies from rently to armor'
      source:
        class: 'Postgres::Source::Base'
        database_name: 'armor'
        batch_size: 1000
        source_table_name: 'users'
        columns:
          - id
          - fullname
          - created_at
          - updated_at
          - salesforce_id
          - rently_id
          - enable_multifamily
          - platform_mode
          - authentication_status

      destination:
        class: 'Postgres::Destination::Base'
        database_name: 'armor'
        destination_table_name: 'users'
        columns:
          - id
          - fullname
          - created_at
          - updated_at
          - salesforce_id
          - rently_id
          - enable_multifamily
          - platform_mode
          - authentication_status
        primary_key: 'id'
        upsert_keys:
          - 'id'