rently:
  host: <%= ENV['POSTGRES_RENTLY_DB_HOST'] %>
  port: <%= ENV['POSTGRES_RENTLY_DB_PORT'] %>
  dbname: <%= ENV['POSTGRES_RENTLY_DBNAME'] %>
  user: <%= ENV['POSTGRES_RENTLY_USER'] %>
  password: <%= ENV['POSTGRES_RENTLY_PASSWORD'] %>

armor:
  host: <%= ENV['POSTGRES_ARMOR_DB_HOST'] %>
  port: <%= ENV['POSTGRES_ARMOR_DB_PORT'] %>
  dbname: <%= ENV['POSTGRES_ARMOR_DBNAME'] %>
  user: <%= ENV['POSTGRES_ARMOR_USER'] %>
  password: <%= ENV['POSTGRES_ARMOR_PASSWORD'] %>
